// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC4mYbGZOWvVc0F0TGffzzT-wF_70F-o8',
    appId: '1:50014509455:web:aeffaba088811ca49293fa',
    messagingSenderId: '50014509455',
    projectId: 'general-b123d',
    authDomain: 'general-b123d.firebaseapp.com',
    storageBucket: 'general-b123d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAULRE0wucnI38MgL3B3b_IqFVpihpkBbI',
    appId: '1:50014509455:android:5d70897cccce41a89293fa',
    messagingSenderId: '50014509455',
    projectId: 'general-b123d',
    storageBucket: 'general-b123d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk5JoUusnJ3JszY2j-nQecuphil-DRNQI',
    appId: '1:50014509455:ios:6a397ee3c8b0979a9293fa',
    messagingSenderId: '50014509455',
    projectId: 'general-b123d',
    storageBucket: 'general-b123d.firebasestorage.app',
    androidClientId: '50014509455-se696o95rl17h7i23qjfdnfg1ubr06m3.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseManager',
  );

}